// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Drive.h"
#include "Commands/Intake_Eject.h"
#include "Commands/Intake_Load.h"
#include "Commands/Intake_Lower.h"
#include "Commands/Intake_Raise.h"
#include "Commands/Lift_Down.h"
#include "Commands/Lift_Up.h"
#include "Commands/SetLeftSpeed.h"
#include "Commands/SetRightSpeed.h"
#include "Commands/Turn.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    stick3.reset(new Joystick(2));
    
    stick2.reset(new Joystick(1));
    
    stick.reset(new Joystick(0));
    

    // SmartDashboard Buttons
    SmartDashboard::PutData("Lift_Up", new Lift_Up());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getstick() {
   return stick;
}

std::shared_ptr<Joystick> OI::getstick2() {
   return stick2;
}

std::shared_ptr<Joystick> OI::getstick3() {
   return stick3;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
